
spring:
  application:
    name: licensing-service
  profiles:
    active: test
  config:
    import: ${CONFIG_SERVER_URL:configserver:http://localhost:8071}



resilience4j:
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: 50
        sliding-window-size: 5
        minimum-number-of-calls: 3
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
    instances:
      licenseService:
        base-config: default
      organizationService:
        base-config: default

