
spring:
  messages:
    encoding: UTF-8

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true


eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/

  liquibase:
    enabled: false


resilience4j.circuitbreaker:
  instances:
    organizationDbCircuitBreaker:
      failure-rate-threshold: 60
      sliding-window-size: 20
      minimum-number-of-calls: 5
      wait-duration-in-open-state: 10s
      permitted-number-of-calls-in-half-open-state: 3

resilience4j.retry:
  instances:
    organizationDbRetry:
      max-attempts: 3
      wait-duration: 500ms


resilience4j.ratelimiter:
  instances:
    organizationServiceRateLimiter:
      limitForPeriod: 5
      limitRefreshPeriod: 1s
      timeoutDuration: 0