
spring:
  messages:
    encoding: UTF-8

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true


eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/

  liquibase:
    enabled: false
